project:
  type: book
  output-dir: docs

IP: 35.89.32.86
engine: knitr
code-line-numbers: true

book:
  title: "Epigenomics Data Analysis"
  page-footer:
    left: |
      Epigenomics Data Analysis |  
      J. Serizay
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://js2264.github.io/NGS_Physalia_2023/
  repo-url: https://github.com/js2264/NGS-Physalia/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - content/program.qmd
    - content/Rstudio.qmd
    - content/prerequisites.qmd
    - part: "Day 1"
      chapters: 
        - content/day1/Lecture1_introduction.qmd
        - content/day1/Lecture2_processing.qmd
        - content/day1/Demo1_MNase-seq_processing.qmd
        - content/day1/Lab1_MNase-seq_processing.qmd
    - part: "Day 2"
      chapters:
        - content/day2/Lecture3_workflows.qmd
        - content/day2/Lecture4_ATACseq.qmd
        - content/day2/Lecture5_R-101.qmd
        - content/day2/Demo2_ATAC-seq_processing.qmd
        - content/day2/Lab2_ATAC-seq_analysis.qmd
    - part: "Day 3"
      chapters:
        - content/day3/Lecture6_ChIPseq.qmd
        - content/day3/Lecture7_R-201.qmd
        - content/day3/Demo3_ChIP-seq_processing.qmd
        - content/day3/Lab3_ChIP-seq_analysis.qmd
    - part: "Day 4"
      chapters:
        - content/day4/Lecture8_RNAseq.qmd
        - content/day4/Lecture9_R-301.qmd
        - content/day4/Demo4_RNA-seq_processing.qmd
        - content/day4/Lab4_RNA-seq_analysis.qmd
    - part: "Day 5"
        - content/day5/Lecture10_HiC.qmd
        - content/day5/Lecture11_GO-GSEA.qmd
        - content/day5/Demo5_Bioc-resources.qmd
        - content/day5/Lab5_data-integration.qmd
    - content/extra.qmd

format:
  html:
    default-image-extension: pdf
    theme:
      - cosmo
      - theme.scss
    code-link: true
    author-meta: "J. Serizay"
    highlight-style: atom-one-dark.theme
    citations-hover: true
    toc: true
    toc-float: 
      collapsed: false
    toc-depth: 3
    grid:
      gutter-width: 1.5em
      sidebar-width: 500px
      body-width: 1200px
      margin-width: 400px
    website: 
      sidebar: 
        style: "docked"
        search: true
        collapse-level: 5

editor: visual
