name: 
    epigenomics
channels:
    - bioconda
    - conda-forge
dependencies:
    - numpy
    - fastqc
    - trim-galore
    - macs2
    - idr
    - meme
    - subread
    - star
    - yapc
    - pairtools
    - bedtools
    - hicstuff
    - chromosight
    - bwa-mem2
    - pandas<3.0.0
    - deeptools
