name: 
    epigenomics
channels:
    - bioconda
    - conda-forge
dependencies:
    - numpy>=2.0.0
    - fastqc
    - trim-galore
    # - deeptools
    - macs2
    - meme
    - subread
    - star
    - yapc
    - bedtools
    - hicstuff
    - chromosight
    - pip: 
        - deeptools
