name: Render & publish

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout repository
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            persist-credentials: false

        # This installs quarto
        - name: Installs quarto 
          uses: quarto-dev/quarto-actions/setup@v2
          with:
            tinytex: true 
          
        # This installs quarto
        - name: Renders book
          uses: quarto-dev/quarto-actions/publish@v2
          with:
            target: gh-pages
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
        